version: 2

project_name: timesheet

builds:
  - id: timesheet
    main: ./main.go
    binary: timesheet
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

archives: []  # no tar.gz — raw binaries only

checksum:
  name_template: "checksums.txt"

changelog:
  use: github

release:
  github:
    owner: srikanth-karthi
    name: Timesheet-cli-application

